# Generated by Django 3.2.15 on 2022-11-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0011_capping_non_required_crate_greater_than_one")]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="description",
            field=models.TextField(blank=True, default=""),
        )
    ]
