# Generated by Django 3.2.15 on 2023-03-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0012_scenario_description")]

    operations = [
        migrations.AddField(
            model_name="sensitivityanalysis",
            name="mvs_version",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="simulation",
            name="mvs_version",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
