# Generated by Django 3.2.19 on 2023-06-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0014_alter_viewer_user")]

    operations = [
        migrations.AlterField(
            model_name="economicdata",
            name="currency",
            field=models.CharField(
                choices=[
                    ("", "Choose..."),
                    ("EUR", "EUR (€)"),
                    ("USD", "USD ($)"),
                    ("NOK", "NOK (kr)"),
                    ("INR", "INR (₹)"),
                    ("GBP", "GBP (£)"),
                ],
                max_length=3,
            ),
        )
    ]
