# Generated by Django 3.2.19 on 2023-06-16 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("projects", "0015_alter_economicdata_currency")]

    operations = [
        migrations.CreateModel(
            name="ParameterChangeTracker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("old_value", models.TextField(null=True)),
                ("new_value", models.TextField(null=True)),
                (
                    "parameter_category",
                    models.CharField(
                        choices=[
                            ("asset", "asset"),
                            ("project", "project"),
                            ("scenario", "scenario"),
                            ("constraint", "constraint"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "parameter_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("scalar", "scalar"),
                            ("vector", "vector"),
                            ("string", "string"),
                            ("bool", "bool"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.asset",
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.simulation",
                    ),
                ),
            ],
        )
    ]
