# Generated by Django 3.2.19 on 2023-06-16 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("projects", "0016_parameterchangetracker")]

    operations = [
        migrations.CreateModel(
            name="AssetChangeTracker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("asset_dto", models.TextField(blank=True, null=True)),
                (
                    "action",
                    models.SmallIntegerField(choices=[(0, "delete"), (0, "create")]),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.simulation",
                    ),
                ),
            ],
        )
    ]
