# Generated by Django 3.2.19 on 2023-06-29 01:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0017_assetchangetracker")]

    operations = [
        migrations.AlterField(
            model_name="economicdata",
            name="tax",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        )
    ]
