# Generated by Django 4.1 on 2023-08-18 17:59

from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import projects.models.base_models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0018_alter_economicdata_tax"),
    ]

    operations = [
        migrations.CreateModel(
            name="Timeseries",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=120)),
                (
                    "values",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(),
                        default=projects.models.base_models.get_default_timeseries,
                        size=None,
                    ),
                ),
                (
                    "units",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Wh", "Wh"),
                            ("kWh", "kWh"),
                            ("MWh", "MWh"),
                            ("GWh", "GWh"),
                            ("TWh", "TWh"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("other", "Other"),
                            ("demand", "Demand"),
                            ("supply", "Supply"),
                        ],
                        max_length=6,
                        null=True,
                    ),
                ),
                (
                    "ts_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Choose..."),
                            ("source", "source"),
                            ("sink", "sink"),
                            ("transformer", "transformer"),
                            ("storage", "storage"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "open_source",
                    models.BooleanField(
                        choices=[(True, "Yes"), (False, "No")], default=False
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("end_time", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "time_step",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.scenario",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        )
    ]
