# Generated by Django 4.2.4 on 2023-09-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0019_timeseries")]

    operations = [
        migrations.AlterField(
            model_name="economicdata",
            name="currency",
            field=models.CharField(
                choices=[
                    ("", "Choose..."),
                    ("EUR", "EUR (€)"),
                    ("USD", "USD ($)"),
                    ("NOK", "NOK (kr)"),
                    ("INR", "INR (₹)"),
                    ("GBP", "GBP (£)"),
                    ("NGN", "NGN (₦)"),
                ],
                max_length=3,
            ),
        )
    ]
