# Generated by Django 4.2.4 on 2023-10-13 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0020_alter_economicdata_currency")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="opex_var_extra",
            field=models.FloatField(
                blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        )
    ]
