# Generated by Django 4.2.4 on 2024-02-07 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_asset_opex_var_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='economicdata',
            name='exchange_rate',
            field=models.FloatField(default=774, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
