# Generated by Django 4.2.4 on 2024-03-22 00:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0022_economicdata_exchange_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="economicdata",
            name="discount",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="economicdata",
            name="exchange_rate",
            field=models.FloatField(
                default=774,
                help_text="Price of the given currency in relation to USD",
                validators=[django.core.validators.MinValueValidator(0.0)],
            ),
        ),
    ]
