# Generated by Django 5.1.3 on 2025-01-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_bus_price_alter_assettype_asset_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="kobo_survey_id",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="kobo_survey_url",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
