# Generated by Django 5.1.3 on 2025-10-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_project_kobo_survey_id_project_kobo_survey_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="economicdata",
            name="population",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="altitude",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
