# Generated by Django 5.1.3 on 2025-11-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_economicdata_population_project_altitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="economicdata",
            name="currency",
            field=models.CharField(
                choices=[
                    ("", "Choose..."),
                    ("EUR", "EUR (€)"),
                    ("USD", "USD ($)"),
                    ("NOK", "NOK (kr)"),
                    ("INR", "INR (₹)"),
                    ("GBP", "GBP (£)"),
                    ("MAD", "MAD (DH)"),
                    ("NGN", "NGN (₦)"),
                    ("ZAR", "ZAR (R)"),
                ],
                max_length=3,
            ),
        ),
    ]
