# Generated by Django 5.1.3 on 2026-02-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_alter_economicdata_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="economicdata",
            name="population",
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
