# Generated by Django 4.2.4 on 2023-10-11 20:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_alter_economicdata_currency"),
        ("business_model", "0002_alter_businessmodel_model_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquityData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("debt_start", models.IntegerField()),
                (
                    "grant_share",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Share of grant for assets (%)",
                    ),
                ),
                (
                    "debt_share",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Share of the external debt (%)",
                    ),
                ),
                (
                    "debt_interest_MG",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Interest rate for external loan: mini-grid (%)",
                    ),
                ),
                (
                    "debt_interest_SHS",
                    models.FloatField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Interest rate for external loan: SHS (%)",
                    ),
                ),
                (
                    "equity_interest_MG",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Interest rate for external equity: mini-grid (%)",
                    ),
                ),
                (
                    "equity_interest_SHS",
                    models.FloatField(
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                        verbose_name="Interest rate for external equity: SHS (%)",
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="projects.scenario"
                    ),
                ),
            ],
        )
    ]
