# Generated by Django 4.2.4 on 2023-10-16 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("business_model", "0003_equitydata")]

    operations = [
        migrations.AddField(
            model_name="equitydata",
            name="fuel_price_increase",
            field=models.FloatField(
                blank=True,
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
                verbose_name="Yearly increase of fuel price (%)",
            ),
        )
    ]
