# Generated by Django 4.2.4 on 2024-01-22 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_model", "0007_equitydata_equity_community_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equitydata",
            name="debt_share",
            field=models.FloatField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100.0),
                ],
                verbose_name="Share of the external debt (%)",
            ),
        ),
    ]
