# Generated by Django 4.2.4 on 2024-02-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_model', '0008_alter_equitydata_debt_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitydata',
            name='estimated_tariff',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
