# Generated by Django 4.2.4 on 2024-02-14 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_model', '0009_equitydata_estimated_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='equitydata',
            name='debt_interest_replacement',
            field=models.FloatField(default=0.11, help_text='Assumed interest rate for loan used for asset replacement', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Interest rate for replacement loan (%)'),
        ),
        migrations.AddField(
            model_name='equitydata',
            name='grace_period',
            field=models.IntegerField(default=1, help_text='Number of years to the first repayment of principal', validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='equitydata',
            name='loan_maturity',
            field=models.IntegerField(default=10, help_text='Number of years to repay the loan', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='equitydata',
            name='debt_interest_MG',
            field=models.FloatField(default=0.11, help_text='Assumed interest rate for loan at project start', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Interest rate for external loan (%)'),
        ),
        migrations.AlterField(
            model_name='equitydata',
            name='equity_community_amount',
            field=models.FloatField(default=0, help_text='Amount of equity the community would be able to mobilize', verbose_name='Community equity (Million NGN)'),
        ),
        migrations.AlterField(
            model_name='equitydata',
            name='equity_developer_amount',
            field=models.FloatField(default=0, help_text='Amount of equity the mini-grid company would be able to mobilize', verbose_name='Mini-grid company equity (Million NGN)'),
        ),
        migrations.AlterField(
            model_name='equitydata',
            name='equity_interest_MG',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Interest rate for external equity: mini-grid (%)'),
        ),
        migrations.AlterField(
            model_name='equitydata',
            name='fuel_price_increase',
            field=models.FloatField(blank=True, default=0, help_text='Assumed yearly increase of fuel price (%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='equitydata',
            name='grant_share',
            field=models.FloatField(default=0.6, help_text='Share of grant for assets provided by REA or other institutions', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Grant share (%)'),
        ),
    ]
