# Generated by Django 4.2.4 on 2024-03-04 13:53

import business_model.helpers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_model", "0010_equitydata_debt_interest_replacement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equitydata",
            name="debt_interest_MG",
            field=models.FloatField(
                default=0.11,
                help_text="Assumed interest rate for loan at project start",
                validators=[business_model.helpers.validate_percent],
                verbose_name="Interest rate for external loan (%)",
            ),
        ),
        migrations.AlterField(
            model_name="equitydata",
            name="debt_interest_SHS",
            field=models.FloatField(
                null=True,
                validators=[business_model.helpers.validate_percent],
                verbose_name="Interest rate for external loan: SHS (%)",
            ),
        ),
        migrations.AlterField(
            model_name="equitydata",
            name="debt_interest_replacement",
            field=models.FloatField(
                default=0.11,
                help_text="Assumed interest rate for loan used for asset replacement",
                validators=[business_model.helpers.validate_percent],
                verbose_name="Interest rate for replacement loan (%)",
            ),
        ),
        migrations.AlterField(
            model_name="equitydata",
            name="debt_share",
            field=models.FloatField(
                default=0,
                validators=[business_model.helpers.validate_percent],
                verbose_name="Share of the external debt (%)",
            ),
        ),
        migrations.AlterField(
            model_name="equitydata",
            name="equity_interest_MG",
            field=models.FloatField(
                default=0,
                validators=[business_model.helpers.validate_percent],
                verbose_name="Interest rate for external equity: mini-grid (%)",
            ),
        ),
        migrations.AlterField(
            model_name="equitydata",
            name="equity_interest_SHS",
            field=models.FloatField(
                null=True,
                validators=[business_model.helpers.validate_percent],
                verbose_name="Interest rate for external equity: SHS (%)",
            ),
        ),
        migrations.AlterField(
            model_name="equitydata",
            name="fuel_price_increase",
            field=models.FloatField(
                blank=True,
                default=0,
                help_text="Assumed yearly increase of fuel price (%)",
                validators=[business_model.helpers.validate_percent],
            ),
        ),
        migrations.AlterField(
            model_name="equitydata",
            name="grant_share",
            field=models.FloatField(
                default=0.6,
                help_text="Share of grant for assets provided by REA or other institutions",
                validators=[business_model.helpers.validate_percent],
                verbose_name="Grant share (%)",
            ),
        ),
    ]
