# Generated by Django 4.2.4 on 2023-09-11 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("projects", "0019_timeseries"), ("cp_nigeria", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ConsumerGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_consumers", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ConsumerType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("consumer_type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DemandTimeseries",
            fields=[
                (
                    "timeseries_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.timeseries",
                    ),
                ),
                (
                    "consumer_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cp_nigeria.consumertype",
                    ),
                ),
            ],
            bases=("projects.timeseries",),
        ),
        migrations.RemoveField(model_name="usergroup", name="facility_type"),
        migrations.RemoveField(model_name="usergroup", name="user_type"),
        migrations.DeleteModel(name="FacilityType"),
        migrations.DeleteModel(name="UserGroup"),
        migrations.DeleteModel(name="UserType"),
        migrations.AddField(
            model_name="consumergroup",
            name="consumer_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cp_nigeria.consumertype",
            ),
        ),
        migrations.AddField(
            model_name="consumergroup",
            name="timeseries",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cp_nigeria.demandtimeseries",
            ),
        ),
    ]
