# Generated by Django 4.2.4 on 2023-09-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cp_nigeria", "0002_consumergroup_consumertype_demandtimeseries_and_more")
    ]

    operations = [
        migrations.AddField(
            model_name="consumergroup",
            name="expected_consumer_increase",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="consumergroup",
            name="expected_demand_increase",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
