# Generated by Django 4.2.4 on 2023-09-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cp_nigeria", "0003_consumergroup_expected_consumer_increase_and_more")
    ]

    operations = [migrations.DeleteModel(name="Project")]
