# Generated by Django 4.2.4 on 2023-09-29 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_alter_economicdata_currency'),
        ('cp_nigeria', '0004_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumergroup',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AlterField(
            model_name='consumergroup',
            name='expected_consumer_increase',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumergroup',
            name='expected_demand_increase',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
