# Generated by Django 4.2.4 on 2023-10-05 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_alter_economicdata_currency"),
        ("cp_nigeria", "0005_consumergroup_project_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Options",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_case", models.TextField(default="")),
                ("main_grid", models.BooleanField(null=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="projects.project"
                    ),
                ),
            ],
        )
    ]
