# Generated by Django 4.2.4 on 2023-10-09 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_community_project_community'),
        ('cp_nigeria', '0006_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumergroup',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.community'),
        ),
    ]
