# Generated by Django 4.2.4 on 2023-10-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("projects", "0020_alter_economicdata_currency"), ("cp_nigeria", "0006_options")]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="projects.project"
                    ),
                ),
                (
                    "pv_timeseries",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="projects.timeseries"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="consumergroup",
            name="community",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="cp_nigeria.community"
            ),
        ),
        migrations.AddField(
            model_name="options",
            name="community",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="cp_nigeria.community"
            ),
        ),
    ]
