# Generated by Django 4.2.4 on 2023-11-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_nigeria', '0007_community_consumergroup_community_options_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='shs_threshold',
            field=models.TextField(blank=True, default='very_low'),
        ),
    ]
