# Generated by Django 4.2.4 on 2023-11-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("projects", "0021_asset_opex_var_extra"), ("cp_nigeria", "0008_options_shs_threshold")]

    operations = [
        migrations.RemoveField(model_name="community", name="project"),
        migrations.AlterField(
            model_name="community",
            name="pv_timeseries",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="projects.timeseries"),
        ),
        migrations.AlterField(
            model_name="consumergroup",
            name="timeseries",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="cp_nigeria.demandtimeseries"
            ),
        ),
    ]
