# Generated by Django 4.2.4 on 2024-03-22 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0023_alter_economicdata_discount_and_more"),
        ("cp_nigeria", "0009_remove_community_project_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImplementationPlanContent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("demand_table", models.TextField()),
                ("cost_table", models.TextField()),
                ("capex_table", models.TextField()),
                ("system_table", models.TextField()),
                ("financial_kpi_table", models.TextField()),
                ("financing_structure_table", models.TextField()),
                ("stacked_timeseries_graph", models.TextField()),
                ("mini_grid_demand_graph", models.TextField()),
                ("capex_graph", models.TextField()),
                ("cash_flow_graph", models.TextField()),
                ("system_costs_graph", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="projects.project"
                    ),
                ),
            ],
        ),
    ]
