# Generated by Django 4.2.4 on 2024-03-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cp_nigeria", "0010_implementationplancontent"),
    ]

    operations = [
        migrations.AddField(
            model_name="options",
            name="demand_coverage_factor",
            field=models.FloatField(blank=True, default=1),
        ),
    ]
