# Generated by Django 4.2.4 on 2024-03-25 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_alter_economicdata_discount_and_more'),
        ('cp_nigeria', '0010_implementationplancontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implementationplancontent',
            name='project',
        ),
        migrations.AddField(
            model_name='implementationplancontent',
            name='simulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.simulation'),
        ),
    ]
