# Generated by Django 4.2.4 on 2024-04-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_nigeria', '0011_remove_implementationplancontent_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementationplancontent',
            name='opex_graph',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='implementationplancontent',
            name='opex_table',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='implementationplancontent',
            name='capex_graph',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='implementationplancontent',
            name='capex_table',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='implementationplancontent',
            name='cash_flow_graph',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='implementationplancontent',
            name='cost_table',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='implementationplancontent',
            name='demand_table',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='implementationplancontent',
            name='financial_kpi_table',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='implementationplancontent',
            name='financing_structure_table',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='implementationplancontent',
            name='mini_grid_demand_graph',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='implementationplancontent',
            name='stacked_timeseries_graph',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='implementationplancontent',
            name='system_costs_graph',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='implementationplancontent',
            name='system_table',
            field=models.TextField(blank=True, default=''),
        ),
    ]
