# Generated by Django 4.2.4 on 2024-04-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cp_nigeria', '0012_implementationplancontent_opex_graph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='demand_coverage_factor',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
