# Generated by Django 5.1.3 on 2025-09-13 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                ("question_id", models.CharField(max_length=30, primary_key=True, serialize=False)),
                ("question", models.TextField()),
                ("subquestion", models.TextField(null=True)),
                ("possible_answers", models.TextField(null=True)),
                ("multiple_answers", models.BooleanField(default=False)),
                ("answer_type", models.CharField(max_length=8)),
                ("description", models.TextField(default="")),
                (
                    "category",
                    models.CharField(
                        choices=[("components", "Components"), ("crops", "Crops"), ("water", "Water")],
                        max_length=60,
                        null=True,
                    ),
                ),
                (
                    "subquestion_to",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="wefe.surveyquestion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.TextField(null=True)),
                ("scenario_id", models.IntegerField()),
                (
                    "question",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="wefe.surveyquestion"),
                ),
            ],
        ),
    ]
