# Generated by Django 5.1.3 on 2025-09-13 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wefe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="matrix_answers",
            field=models.BooleanField(default=False),
        ),
    ]
