# Generated by Django 5.1.3 on 2025-10-28 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_project_kobo_survey_id_project_kobo_survey_url"),
        ("wefe", "0002_surveyquestion_matrix_answers"),
    ]

    operations = [
        migrations.CreateModel(
            name="WEFESimulation",
            fields=[
                (
                    "simulation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="projects.simulation",
                    ),
                ),
                (
                    "app",
                    models.CharField(
                        choices=[
                            ("weather_data", "Weather Data API"),
                            ("wefedemand", "WEFEDemand API"),
                            ("sim_server", "WEFE Simulation Server"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("projects.simulation",),
        ),
    ]
