# Generated by Django 5.1.3 on 2025-11-02 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_project_kobo_survey_id_project_kobo_survey_url'),
        ('wefe', '0002_surveyquestion_matrix_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='WEFESimulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('elapsed_seconds', models.FloatField(null=True)),
                ('mvs_token', models.CharField(max_length=200, null=True)),
                ('mvs_version', models.CharField(max_length=15, null=True)),
                ('status', models.CharField(choices=[('ERROR', 'ERROR'), ('DONE', 'DONE'), ('PENDING', 'PENDING'), ('MODIFIED', 'MODIFIED')], default='PENDING', max_length=20)),
                ('results', models.TextField(max_length=30000000.0, null=True)),
                ('errors', models.TextField(null=True)),
                ('app', models.CharField(choices=[('weather_data', 'Weather Data API'), ('wefedemand', 'WEFEDemand API'), ('sim_server', 'WEFE Simulation Server')], max_length=30)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.scenario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
