# Generated by Django 5.1.3 on 2025-11-04 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_project_kobo_survey_id_project_kobo_survey_url"),
        ("wefe", "0003_wefesimulation"),
    ]

    operations = [
        migrations.CreateModel(
            name="MOOWeights",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_cost", models.FloatField(default=1)),
                ("co2_emissions", models.FloatField(default=0)),
                ("land_requirements", models.FloatField(default=0)),
                ("water_footprint", models.FloatField(default=0)),
                ("scenario", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="projects.scenario")),
            ],
        ),
    ]
