"""
Django settings for EPA project.

Generated by 'django-admin startproject' using Django 3.0.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import environ
from pathlib import Path
import sys

from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Root dir is a parent directory
ROOT_DIR = environ.Path(__file__) - 2

# Read environment variables
env = environ.Env()

# Read .env file
# OS environment variables take precedence over variables from .env file
env.read_env(str(ROOT_DIR.path(".env")))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "cdn_static_root"
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "django_plotly_dash.finders.DashAssetFinder",
    "django_plotly_dash.finders.DashComponentFinder",
    "django_plotly_dash.finders.DashAppDirectoryFinder",
]

if DEBUG is True:
    STATICFILES_FINDERS.append("sass_processor.finders.CssFinder")
    SASS_PROCESSOR_ROOT = STATIC_ROOT
    SASS_PRECISION = 8
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("EPA_SECRET_KEY", default="v@p9^=@lc3#1u_xtx*^xhrv0l3li1(+8ik^k@g-_bzmexb0$7n")
ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = list()
if env("TRUSTED_HOST", default=None) is not None:
    CSRF_TRUSTED_ORIGINS.append(f"https://{env('TRUSTED_HOST')}")
    CSRF_TRUSTED_ORIGINS.append(f"http://{env('TRUSTED_HOST')}")
# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.forms",
    "users.apps.UsersConfig",
    "projects.apps.ProjectsConfig",
    "dashboard.apps.DashboardConfig",
    "cp_nigeria.apps.CPNigeriaConfig",
    "wefe.apps.WefeConfig",
    "business_model.apps.BusinessModelConfig",
    # 3rd Party
    "crispy_forms",
    "crispy_bootstrap5",
    "django_q",
    "django_plotly_dash.apps.DjangoPlotlyDashConfig",
]

if DEBUG is True:
    INSTALLED_APPS.append("sass_processor")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django_plotly_dash.middleware.BaseMiddleware",
    "django_plotly_dash.middleware.ExternalRedirectionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

FILE_UPLOAD_HANDLERS = [
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
]

ROOT_URLCONF = "epa.urls"

FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(BASE_DIR / "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "epa.context_processors.debug",
            ]
        },
    }
]

WSGI_APPLICATION = "epa.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
# SQLite does not support ArrayField, so PostgreSQL is needed as engine
DATABASES = {
    "default": {
        "ENGINE": env("SQL_ENGINE", default="django.db.backends.postgresql"),
        "NAME": env("SQL_DATABASE"),  # required
        "USER": env("SQL_USER", default=None),
        "PASSWORD": env("SQL_PASSWORD", default=None),
        "HOST": env("SQL_HOST", default=None),
        "PORT": env.int("SQL_PORT", default=5432),
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en"

LOCALE_PATHS = (BASE_DIR / "locale",)

LANGUAGES = [("en", "English")]

TIME_ZONE = "Europe/Copenhagen"

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Other configs

AUTH_USER_MODEL = "users.CustomUser"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "wefe_home"
LOGOUT_REDIRECT_URL = "wefe_home"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Please note, we don't use Django's internal email system,
# we implement our own, using exchangelib
USE_EXCHANGE_EMAIL_BACKEND = env.bool("USE_EXCHANGE_EMAIL_BACKEND", default=True)
# The Exchange account which sends emails
EXCHANGE_ACCOUNT = env("EXCHANGE_ACCOUNT", default="dummy@dummy.com")
EXCHANGE_PW = env("EXCHANGE_PW", default="dummypw")
EXCHANGE_EMAIL = env("EXCHANGE_EMAIL", default="dummy@dummy.com")
EXCHANGE_SERVER = env("EXCHANGE_SERVER", default="dummy.com")
# Email addresses to which feedback emails will be sent
RECIPIENTS = env.list("RECIPIENTS", default=["dummy@dummy.com", "dummy2@dummy.com"])
EMAIL_SUBJECT_PREFIX = env("EMAIL_SUBJECT_PREFIX", default="[wefe_plan] ")

MESSAGE_TAGS = {
    messages.DEBUG: "alert-info",
    messages.INFO: "alert-info",
    messages.SUCCESS: "alert-success",
    messages.WARNING: "alert-warning",
    messages.ERROR: "alert-danger",
}

USE_PROXY = env.bool("USE_PROXY", default=True)
PROXY_ADDRESS_LINK = env("PROXY_ADDRESS", default="http://proxy:port")
PROXY_CONFIG = ({"http://": PROXY_ADDRESS_LINK, "https://": PROXY_ADDRESS_LINK}) if USE_PROXY else ({})

MVS_API_HOST = env("MVS_API_HOST", default="https://mvs-eland.rl-institut.de")
MVS_POST_URL = f"{MVS_API_HOST}/sendjson/"
MVS_GET_URL = f"{MVS_API_HOST}/check/"
MVS_LP_FILE_URL = f"{MVS_API_HOST}/get_lp_file/"
MVS_SA_POST_URL = f"{MVS_API_HOST}/sendjson/openplan/sensitivity-analysis"
MVS_SA_GET_URL = f"{MVS_API_HOST}/check-sensitivity-analysis/"

# Allow iframes to show in page
X_FRAME_OPTIONS = "SAMEORIGIN"

# API token to fetch exchange rates
EXCHANGE_RATES_API_TOKEN = env("EXCHANGE_RATES_API_TOKEN", default=None)
if EXCHANGE_RATES_API_TOKEN is None:
    EXCHANGE_RATES_URL = None
else:
    EXCHANGE_RATES_URL = f"https://v6.exchangerate-api.com/v6/{EXCHANGE_RATES_API_TOKEN}/latest/USD"

# API to connect with KoboToolbox
KOBO_API_URL = "https://eu.kobotoolbox.org/api/v2"
KOBO_API_TOKEN = env("KOBO_API_TOKEN", default=None)

# API to get weather data
WEATHER_DATA_API_HOST = env("WEATHER_DATA_API_HOST", default=None)

# RenewablesNinja API
RN_TOKEN = env("RN_API_TOKEN", default=None)
RN_API_BASE = "https://www.renewables.ninja/api/"

# altitude API
OPEN_METEO_URL = "https://api.open-meteo.com/v1/"
OPEN_TOPO_URL = "https://api.opentopodata.org/v1/"

# WEFEDemand API
WEFEDEMAND_API_HOST = env("WEFEDEMAND_API", default=None)
WEFEDEMAND_POST_URL = f"{WEFEDEMAND_API_HOST}/sendjson"
WEFEDEMAND_GET_URL = f"{WEFEDEMAND_API_HOST}/check/"

# WEFESIM API
WEFESIM_API_HOST = env("WEFESIM_API", default=None)
WEFESIM_POST_URL = f"{WEFESIM_API_HOST}/sendjson/"
WEFESIM_GET_URL = f"{WEFESIM_API_HOST}/check/"

# WEFEConfigurator settings
COMPONENT_TEMPLATES_PATH = str(BASE_DIR / "static" / "wefe_configurator" / "component_library" / "components")
COMPONENT_HELPERS_PATH = str(BASE_DIR / "static" / "wefe_configurator" / "component_library" / "helpers")

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "dtlnm": {
            "format": "%(asctime)s - %(levelname)8s - %(name)s - %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        }
    },
    "handlers": {
        "info_file": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": "django_epa_info.log",
            "formatter": "dtlnm",
        },
        "warnings_file": {
            "level": "WARNING",
            "class": "logging.FileHandler",
            "filename": "django_epa_warning.log",
            "formatter": "dtlnm",
        },
        "console": {
            "level": "WARNING",
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
        },
    },
    "loggers": {
        "": {
            "handlers": ["info_file", "warnings_file", "console"],
            "level": "DEBUG",
            "propagate": True,
        },
        "asyncio": {"level": "WARNING"},
    },
}

# DJANGO-Q CONFIGURATION
# source: https://django-q.readthedocs.io/en/latest/configure.html
Q_CLUSTER = {
    "name": "django_q_orm",
    "workers": 4,
    "timeout": 90,
    "retry": 120,
    "queue_limit": 50,
    "orm": "default",
}

# django-plotly-dash settings
X_FRAME_OPTIONS = "SAMEORIGIN"

PLOTLY_COMPONENTS = [
    # Common components (ie within dash itself) are automatically added
    # django-plotly-dash components
    "dpd_components",
    # Other components, as needed
    "dash_bootstrap_components",
]
