#!/bin/bash
echo COLLECTSTATIC
python /src/manage.py collectstatic --noinput
echo UPDATESURVEY
python /src/manage.py update_survey_questions --update
echo MIGRATE
python /src/manage.py showmigrations
python /src/manage.py migrate
python /src/manage.py compilemessages
#python /src/manage.py loaddata 'src/fixtures/fixture.json'
echo $(ls -L 1 --dirsfirst)
gunicorn epa.wsgi:application --bind 0.0.0.0:8000 --workers=1 --timeout=120
