# Generated by Django 3.2.15 on 2022-11-14 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_capping_non_required_crate_greater_than_one"),
        ("dashboard", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlowResults",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flow_data", models.TextField()),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.simulation",
                    ),
                ),
            ],
        )
    ]
